[package]
name = "xlsx-parser-rs"
version = "0.1.0"
authors = ["hongjr03 <hongjr03@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
typst-plugin = ["wasm-minimal-protocol"]
default = ["typst-plugin"]

[dependencies]
umya-spreadsheet = { version = "2.2.2", features = ["js"] }
getrandom = { version = "0.2.15", features = ["custom"] }
wasm-minimal-protocol = { git = "https://github.com/astrale-sharp/wasm-minimal-protocol.git", rev = "637508c", optional = true }
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"

[profile.release]
opt-level = "s"
